version: "3"
services:
  eda:
    build: ./
    user: root
    volumes:
      - ./:/app
    working_dir: /app
    tty: true
    ports:
      - "8890:8890"
    command:
      jupyter lab
        --port=8890
        --ip=0.0.0.0
        --allow-root
        --NotebookApp.token=''
        --no-browser
